
[package]
name = "aoc2015"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
md5 = "0.8"
regex = "1"
serde_json = "1.0"
mission5 = { path = "../../missions/Mission5" }
mission6 = { path = "../../missions/Mission6" }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "day10_comparison"
harness = false
