#!/usr/bin/env pwsh
<#
.SYNOPSIS
    View Day 7 debug output files with interactive features
.DESCRIPTION
    Provides an interactive way to browse, search, and analyze 
    the debug output files generated by Day 7 solutions.
.PARAMETER File
    Specific debug file to view (tab completion available)
.PARAMETER Search
    Search term to highlight in the output
.PARAMETER Lines
    Number of lines to show at a time (default: 20)
.EXAMPLE
    .\view_day07_debug.ps1
    .\view_day07_debug.ps1 -File "day07_debug_output_*.txt"
    .\view_day07_debug.ps1 -Search "wire.*a"
#>

param(
    [string]$File = "",
    [string]$Search = "",
    [int]$Lines = 20
)

function Show-DebugFileBrowser {
    Write-Host "📁 Available Day 7 Debug Files:" -ForegroundColor Cyan
    Write-Host ""
    
    $debugFiles = Get-ChildItem -Filter "day07_debug*.txt" | Sort-Object LastWriteTime -Descending
    
    if ($debugFiles.Count -eq 0) {
        Write-Host "❌ No debug files found. Run .\run_day07_debug.ps1 first!" -ForegroundColor Red
        return $null
    }
    
    for ($i = 0; $i -lt $debugFiles.Count; $i++) {
        $file = $debugFiles[$i]
        $size = [math]::Round($file.Length / 1KB, 2)
        $time = $file.LastWriteTime.ToString("yyyy-MM-dd HH:mm:ss")
        Write-Host "  [$($i + 1)] $($file.Name)" -ForegroundColor Yellow
        Write-Host "      Size: $size KB | Modified: $time" -ForegroundColor Gray
    }
    
    Write-Host ""
    $choice = Read-Host "Select file number (1-$($debugFiles.Count)) or press Enter for latest"
    
    if ([string]::IsNullOrEmpty($choice)) {
        return $debugFiles[0].FullName
    }
    
    $index = $choice -as [int]
    if ($index -and $index -ge 1 -and $index -le $debugFiles.Count) {
        return $debugFiles[$index - 1].FullName
    }
    
    Write-Host "❌ Invalid selection!" -ForegroundColor Red
    return $null
}

function Show-FileContent {
    param($FilePath, $SearchTerm, $PageSize)
    
    if (-not (Test-Path $FilePath)) {
        Write-Host "❌ File not found: $FilePath" -ForegroundColor Red
        return
    }
    
    $content = Get-Content $FilePath
    $totalLines = $content.Count
    
    Write-Host "📄 File: $(Split-Path $FilePath -Leaf)" -ForegroundColor Cyan
    Write-Host "📊 Total lines: $totalLines" -ForegroundColor Gray
    
    if (![string]::IsNullOrEmpty($SearchTerm)) {
        Write-Host "🔍 Search term: $SearchTerm" -ForegroundColor Yellow
        $matchingLines = $content | Select-String $SearchTerm -AllMatches
        Write-Host "📍 Matches found: $($matchingLines.Count)" -ForegroundColor Green
    }
    
    Write-Host ""
    Write-Host "Navigation: [Enter]=Next page, [B]=Back page, [S]=Search, [G]=Go to line, [Q]=Quit" -ForegroundColor Blue
    Write-Host "=" * 80 -ForegroundColor Gray
    
    $currentLine = 0
    
    while ($true) {
        # Show current page
        $endLine = [math]::Min($currentLine + $PageSize - 1, $totalLines - 1)
        
        Write-Host "Lines $($currentLine + 1)-$($endLine + 1) of $totalLines" -ForegroundColor Magenta
        Write-Host "-" * 80 -ForegroundColor Gray
        
        for ($i = $currentLine; $i -le $endLine; $i++) {
            $line = $content[$i]
            $lineNum = $i + 1
            
            # Highlight search terms
            if (![string]::IsNullOrEmpty($SearchTerm) -and $line -match $SearchTerm) {
                Write-Host "$($lineNum.ToString().PadLeft(4)): " -NoNewline -ForegroundColor Green
                $highlighted = $line -replace "($SearchTerm)", "***$1***"
                Write-Host $highlighted -ForegroundColor White
            } else {
                Write-Host "$($lineNum.ToString().PadLeft(4)): $line" -ForegroundColor White
            }
        }
        
        Write-Host "-" * 80 -ForegroundColor Gray
        
        # Get user input
        $userCommand = Read-Host "Command"
        
        switch ($userCommand.ToLower()) {
            "" { 
                # Next page
                if ($endLine -lt $totalLines - 1) {
                    $currentLine = $endLine + 1
                } else {
                    Write-Host "📄 End of file reached!" -ForegroundColor Yellow
                }
            }
            "b" { 
                # Previous page
                if ($currentLine -gt 0) {
                    $currentLine = [math]::Max(0, $currentLine - $PageSize)
                } else {
                    Write-Host "📄 Beginning of file!" -ForegroundColor Yellow
                }
            }
            "s" { 
                # Search
                $SearchTerm = Read-Host "Enter search term"
                if (![string]::IsNullOrEmpty($SearchTerm)) {
                    $searchMatches = $content | Select-String $SearchTerm -AllMatches
                    if ($searchMatches.Count -gt 0) {
                        Write-Host "Found $($searchMatches.Count) matches" -ForegroundColor Green
                        $firstMatch = $searchMatches[0].LineNumber - 1
                        $currentLine = [math]::Max(0, $firstMatch - 5)  # Show some context
                    } else {
                        Write-Host "No matches found!" -ForegroundColor Red
                    }
                }
            }
            "g" { 
                # Go to line
                $lineNum = Read-Host "Enter line number (1-$totalLines)"
                $target = $lineNum -as [int]
                if ($target -and $target -ge 1 -and $target -le $totalLines) {
                    $currentLine = [math]::Max(0, $target - 1)
                } else {
                    Write-Host "Invalid line number!" -ForegroundColor Red
                }
            }
            "q" { 
                return
            }
            default {
                Write-Host "Unknown command: $userCommand" -ForegroundColor Red
                Write-Host "Available: [Enter]=Next, [B]=Back, [S]=Search, [G]=Go to line, [Q]=Quit" -ForegroundColor Blue
            }
        }
        
        Write-Host ""
    }
}

Write-Host "🔧 Day 7 Debug File Viewer" -ForegroundColor Cyan

# Determine which file to view
$targetFile = ""

if (![string]::IsNullOrEmpty($File)) {
    $fileMatches = Get-ChildItem -Filter $File -ErrorAction SilentlyContinue
    if ($fileMatches.Count -eq 1) {
        $targetFile = $fileMatches[0].FullName
    } elseif ($fileMatches.Count -gt 1) {
        Write-Host "Multiple files match '$File':" -ForegroundColor Yellow
        $fileMatches | ForEach-Object { Write-Host "  - $($_.Name)" }
        Write-Host ""
        $targetFile = Show-DebugFileBrowser
    } else {
        Write-Host "No files match '$File'" -ForegroundColor Red
        $targetFile = Show-DebugFileBrowser
    }
} else {
    $targetFile = Show-DebugFileBrowser
}

if (![string]::IsNullOrEmpty($targetFile)) {
    Show-FileContent -FilePath $targetFile -SearchTerm $Search -PageSize $Lines
}