[workspace]
members = [
    "rust_book/Ch1/hello_cargo",
    "rust_book/Ch2/guessing_game", 
    "rust_book/Ch3/variables",
    "rust_book/Ch3/functions",
    "rust_book/Ch3/data_types",
    "rust_book/Ch3/control_flow",
    "rust_book/Ch4/ownership",
    "rust_book/Ch4/references",
    "rust_book/Ch4/slices",
    "rust_book/Ch5/structs",
    "rust_book/Ch5/rectangles",
    "rust_book/Ch5/method_syntax",
    "rust_book/Ch6/defining_enums",
    "rust_book/Ch6/match_operator",
    "rust_book/Ch6/if_let",
    "rust_book/Ch7/crates",
    "rust_book/Ch7/modules",
    "rust_book/Ch7/packages",
    "rust_book/Ch7/paths",
    "rust_book/Ch7/visibility",
    "rust_book/Ch8/vectors",
    "rust_book/Ch8/strings",
    "rust_book/Ch8/hashmaps",
    "rust_book/Ch8/exercises",
    "rust_book/Ch9/unrecoverable_errors",
    "rust_book/Ch9/recoverable_errors",
    "rust_book/Ch9/error_propagation",
    "rust_book/Ch9/exercises",
    "rust_book/Ch10/generics",
    "rust_book/Ch10/traits",
    "rust_book/Ch10/lifetimes",
    "rust_book/Ch11/testing_basics",
    "rust_book/Ch11/test_execution",
    "rust_book/Ch11/test_organization",
    "rust_book/Ch12/accepting_arguments",
    "rust_book/Ch12/reading_files",
    "rust_book/Ch12/refactoring",
    "rust_book/Ch12/testing",
    "rust_book/Ch12/environment_variables",
    "rust_book/Ch12/error_messages",
    "rust_book/Ch12/minigrep",
    "rust_book/Ch14/release_profiles",
    "rust_book/Ch14/publishing_example",
    "rust_book/Ch14/workspace_example/adder",
    "rust_book/Ch14/workspace_example/add-one",
    "rust_book/Ch14/workspace_example/add-two",
    "rust_book/Ch14/install_example",
    "rust_book/Ch14/custom_command",
    "rust_book/Ch15",
    "missions/Mission1",
    "missions/Mission2",
    "missions/Mission3",
    "missions/Mission4",
    "missions/Mission5",
    "missions/Mission6",
    "missions/Mission7",
    "missions/Mission8",
    "missions/Mission9",
    "missions/Mission10",
    "tutorials/Mission1_tut",
    "tutorials/Mission2_tut",
    "tutorials/Mission3_tut",
    "tutorials/Mission4_tut",
    "tutorials/Mission5_tut",
    "tutorials/Mission6_tut",
    "tutorials/Mission7_tut",
    "tutorials/Mission8_tut",
    "tutorials/Mission9_tut",
    "tutorials/Mission10_tut",
    "advanced_examples/Brackets_Basic",
    "advanced_examples/Brackets_Ext", 
    "advanced_examples/competitive_ring_bfs",
    "advanced_examples/competitive_linked_tree",
    "advanced_examples/weasel_evolution",
    "advent_of_code/aoc_pattern_recognition",
    "advent_of_code/aoc2015",
    "advent_of_code/aoc2023",
    "advent_of_code/aoc2024",
    "daily_study/rust_learning_week5_notes",
    "rust_book/Ch16/threads",
    "rust_book/Ch16/message_passing",
    "rust_book/Ch16/shared_state",
    "rust_book/Ch16/sync_send",
    "rust_book/Ch17/futures_basics",
    "rust_book/Ch17/async_concurrency",
    "rust_book/Ch17/async_streams",
    "rust_book/Ch17/async_traits",
    "rust_book/Ch17/hello-async",
    "rust_book/Ch18",
    "rust_book/Ch19",
    "rust_book/Ch20",
    "rust_book/Ch21",
    "rust_for_rustaceans/Ch01/foundations",
    "rust_for_rustaceans/Ch02/types"]

resolver = "3"
