[workspace]
members = [
    "Ch1/hello_cargo",
    "Ch2/guessing_game", 
    "Ch3/variables",
    "Ch3/functions",
    "Ch3/data_types",
    "Ch3/control_flow",
    "Ch4/ownership",
    "Ch4/references",
    "Mission1",
    "Mission2",
    "Mission3",
    "Mission4",
    "Mission4_tut",
    "Mission5",
    "Mission5_tut",
    "Brackets_Basic",
    "Brackets_Ext",
    "competitive_ring_bfs",
    "competitive_linked_tree",
    "aoc_scaffold_templates_with_tests",
    "aoc_pattern_recognition",
    "aoc2015"
]

resolver = "2"