[workspace]
members = [
    "rust_book/Ch1/hello_cargo",
    "rust_book/Ch2/guessing_game", 
    "rust_book/Ch3/variables",
    "rust_book/Ch3/functions",
    "rust_book/Ch3/data_types",
    "rust_book/Ch3/control_flow",
    "rust_book/Ch4/ownership",
    "rust_book/Ch4/references",
    "rust_book/Ch4/slices",
    "rust_book/Ch5/structs",
    "rust_book/Ch5/rectangles",
    "rust_book/Ch5/method_syntax",
    "rust_book/Ch6/defining_enums",
    "rust_book/Ch6/match_operator",
    "rust_book/Ch6/if_let",
    "rust_book/Ch7/crates",
    "rust_book/Ch7/modules",
    "rust_book/Ch7/packages",
    "rust_book/Ch7/paths",
    "rust_book/Ch7/visibility",
    "missions/Mission1",
    "missions/Mission2",
    "missions/Mission3",
    "missions/Mission4",
    "missions/Mission5",
    "missions/Mission6",
    "missions/Mission7",
    "tutorials/Mission4_tut",
    "tutorials/Mission5_tut",
    "tutorials/Mission6_tut",
    "tutorials/Mission7_tut",
    "advanced_examples/Brackets_Basic",
    "advanced_examples/Brackets_Ext", 
    "advanced_examples/competitive_ring_bfs",
    "advanced_examples/competitive_linked_tree",
    "advent_of_code/aoc_pattern_recognition",
    "advent_of_code/aoc2015"
]

resolver = "2"