//! # Project Euler Problem 12: Highly Divisible Triangular Number
//!
//! **Problem Statement:**
//! The sequence of triangle numbers is generated by adding the natural numbers.
//! So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
//!
//! The first ten terms would be:
//! 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
//!
//! Let us list the factors of the first seven triangle numbers:
//!  1: 1
//!  3: 1,3
//!  6: 1,2,3,6
//! 10: 1,2,5,10
//! 15: 1,3,5,15
//! 21: 1,3,7,21
//! 28: 1,2,4,7,14,28
//!
//! We can see that 28 is the first triangle number to have over five divisors.
//!
//! **Question:** What is the value of the first triangle number to have over five hundred divisors?
//!
//! **Answer:** 76,576,500
//!
//! **Performance:** ~X ms (to be benchmarked)
//!
//! ## Approach
//!
//! ### Naive Approach (Too Slow)
//! Generate triangle numbers and count divisors by trial division up to √n.
//! **Issue:** Counting divisors is O(√n) per number, and triangle numbers grow quadratically.
//!
//! ### Optimized Approach Using Prime Factorization
//!
//! **Key Insight:** The number of divisors can be computed from prime factorization!
//!
//! If n = p₁^a₁ × p₂^a₂ × ... × pₖ^aₖ, then:
//! **τ(n) = (a₁ + 1)(a₂ + 1)...(aₖ + 1)**
//!
//! **Why this works:**
//! - Each divisor is formed by choosing exponents 0 ≤ e₁ ≤ a₁, 0 ≤ e₂ ≤ a₂, etc.
//! - For each prime pᵢ, we have (aᵢ + 1) choices of exponent
//! - Total divisors = product of choices
//!
//! **Example:** 28 = 2² × 7¹
//! - Exponents for 2: {0, 1, 2} → 3 choices
//! - Exponents for 7: {0, 1} → 2 choices
//! - Total divisors: 3 × 2 = 6 ✓ (1, 2, 4, 7, 14, 28)
//!
//! ### Additional Optimization: Triangle Number Property
//!
//! Triangle numbers have the form: T(n) = n(n+1)/2
//!
//! **Key observation:** n and (n+1) are consecutive, so gcd(n, n+1) = 1 (coprime!)
//!
//! **Implication:**
//! - If n is even: n = 2k, so T(n) = k(2k+1)
//! - If n is odd: (n+1) = 2k, so T(n) = n × k
//!
//! **Divisor formula:**
//! - τ(T(n)) = τ(n/2) × τ(n+1) if n is even
//! - τ(T(n)) = τ(n) × τ((n+1)/2) if n is odd
//!
//! This avoids factoring the full triangle number—just factor two smaller coprime numbers!

/// Count the number of divisors of n using prime factorization.
///
/// # Algorithm
///
/// 1. Factor n into primes: n = p₁^a₁ × p₂^a₂ × ... × pₖ^aₖ
/// 2. Apply divisor formula: τ(n) = (a₁ + 1)(a₂ + 1)...(aₖ + 1)
///
/// # Complexity
///
/// - **Time:** O(√n) worst case (when n is prime)
/// - **Space:** O(1)
///
/// # Examples
///
/// ```
/// use project_euler::problems::p012::count_divisors;
///
/// assert_eq!(count_divisors(1), 1);    // 1
/// assert_eq!(count_divisors(3), 2);    // 1, 3
/// assert_eq!(count_divisors(6), 4);    // 1, 2, 3, 6
/// assert_eq!(count_divisors(28), 6);   // 1, 2, 4, 7, 14, 28
/// ```
pub fn count_divisors(mut n: u64) -> u64 {
    if n == 0 {
        return 0;
    }
    if n == 1 {
        return 1;
    }

    let mut divisor_count = 1u64;

    // Factor of 2
    if n.is_multiple_of(2) {
        let mut exponent = 0;
        while n.is_multiple_of(2) {
            exponent += 1;
            n /= 2;
        }
        divisor_count *= exponent + 1;
    }

    // Odd factors
    let mut factor = 3u64;
    while factor * factor <= n {
        if n.is_multiple_of(factor) {
            let mut exponent = 0;
            while n.is_multiple_of(factor) {
                exponent += 1;
                n /= factor;
            }
            divisor_count *= exponent + 1;
        }
        factor += 2;
    }

    // Remaining n is prime (exponent = 1)
    if n > 1 {
        divisor_count *= 2; // (1 + 1)
    }

    divisor_count
}

/// Find the first triangle number with more than `min_divisors` divisors.
///
/// # Algorithm
///
/// Uses the optimized approach:
/// - Generate triangle numbers: T(n) = n(n+1)/2
/// - Use coprimality: τ(T(n)) = τ(n/2) × τ(n+1) or τ(n) × τ((n+1)/2)
/// - Count divisors via prime factorization
///
/// # Complexity
///
/// - **Time:** O(k × √T(k)) where k is the index of the answer
/// - **Space:** O(1)
///
/// # Examples
///
/// ```
/// use project_euler::problems::p012::first_triangle_with_divisors;
///
/// assert_eq!(first_triangle_with_divisors(5), 28);   // T(7) = 28 has 6 divisors
/// ```
pub fn first_triangle_with_divisors(min_divisors: u64) -> u64 {
    let mut n = 1u64;

    loop {
        // Calculate divisor count using coprimality property
        let divisor_count = if n.is_multiple_of(2) {
            // n is even: T(n) = (n/2) × (n+1)
            count_divisors(n / 2) * count_divisors(n + 1)
        } else {
            // n is odd: T(n) = n × ((n+1)/2)
            count_divisors(n) * count_divisors(n.div_ceil(2))
        };

        if divisor_count > min_divisors {
            // Calculate the triangle number
            return n * (n + 1) / 2;
        }

        n += 1;
    }
}

/// Solve Project Euler Problem 12.
///
/// Find the first triangle number with over 500 divisors.
pub fn solve() -> u64 {
    first_triangle_with_divisors(500)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_count_divisors_small() {
        assert_eq!(count_divisors(1), 1); // 1
        assert_eq!(count_divisors(2), 2); // 1, 2
        assert_eq!(count_divisors(3), 2); // 1, 3
        assert_eq!(count_divisors(4), 3); // 1, 2, 4
        assert_eq!(count_divisors(6), 4); // 1, 2, 3, 6
    }

    #[test]
    fn test_count_divisors_triangle_numbers() {
        assert_eq!(count_divisors(1), 1); // T(1)
        assert_eq!(count_divisors(3), 2); // T(2)
        assert_eq!(count_divisors(6), 4); // T(3)
        assert_eq!(count_divisors(10), 4); // T(4)
        assert_eq!(count_divisors(15), 4); // T(5)
        assert_eq!(count_divisors(21), 4); // T(6)
        assert_eq!(count_divisors(28), 6); // T(7)
    }

    #[test]
    fn test_count_divisors_powers_of_two() {
        assert_eq!(count_divisors(2), 2); // 2^1: (1+1) = 2
        assert_eq!(count_divisors(4), 3); // 2^2: (2+1) = 3
        assert_eq!(count_divisors(8), 4); // 2^3: (3+1) = 4
        assert_eq!(count_divisors(16), 5); // 2^4: (4+1) = 5
        assert_eq!(count_divisors(32), 6); // 2^5: (5+1) = 6
    }

    #[test]
    fn test_count_divisors_primes() {
        // Primes have exactly 2 divisors (1 and themselves)
        assert_eq!(count_divisors(2), 2);
        assert_eq!(count_divisors(3), 2);
        assert_eq!(count_divisors(5), 2);
        assert_eq!(count_divisors(7), 2);
        assert_eq!(count_divisors(11), 2);
    }

    #[test]
    fn test_count_divisors_composite() {
        // 12 = 2^2 × 3^1 → (2+1)(1+1) = 6
        assert_eq!(count_divisors(12), 6);

        // 20 = 2^2 × 5^1 → (2+1)(1+1) = 6
        assert_eq!(count_divisors(20), 6);

        // 24 = 2^3 × 3^1 → (3+1)(1+1) = 8
        assert_eq!(count_divisors(24), 8);
    }

    #[test]
    fn test_first_triangle_with_divisors_small() {
        // First triangle number with > 5 divisors is 28
        assert_eq!(first_triangle_with_divisors(5), 28);
    }

    #[test]
    fn test_first_triangle_with_divisors_solution() {
        // Problem 12 answer
        let result = first_triangle_with_divisors(500);
        assert_eq!(result, 76_576_500);
    }

    #[test]
    fn test_triangle_number_properties() {
        // Verify T(n) = n(n+1)/2
        let t = |n: u64| n * (n + 1) / 2;

        assert_eq!(t(1), 1);
        assert_eq!(t(2), 3);
        assert_eq!(t(3), 6);
        assert_eq!(t(4), 10);
        assert_eq!(t(7), 28);
    }

    #[test]
    fn test_coprime_property() {
        // For T(7) = 28 = 7 × 8 / 2 = 7 × 4
        // τ(28) = τ(7) × τ(4) = 2 × 3 = 6
        assert_eq!(count_divisors(7) * count_divisors(4), count_divisors(28));

        // For T(8) = 36 = 8 × 9 / 2 = 4 × 9
        // τ(36) = τ(4) × τ(9) = 3 × 3 = 9
        assert_eq!(count_divisors(4) * count_divisors(9), count_divisors(36));
    }
}
