//! # Problem 29: Distinct Powers
//!
//! Consider all integer combinations of a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100.
//! How many distinct terms are in the sequence generated by a^b?
//!
//! For example, with 2 ≤ a ≤ 5, 2 ≤ b ≤ 5, there are 15 distinct terms
//! (since 4² = 2⁴ = 16, causing one duplicate).
//!
//! ## Mathematical Foundation
//!
//! The key insight is that some bases are powers of smaller bases:
//! - 4 = 2², so 4^b = 2^(2b)
//! - 8 = 2³, so 8^b = 2^(3b)
//! - 9 = 3², so 9^b = 3^(2b)
//!
//! Two terms a₁^b₁ and a₂^b₂ are equal iff they share the same **canonical form**
//! (smallest_base, combined_exponent). By reducing every a^b to its canonical
//! representation and collecting into a HashSet, duplicates are eliminated.
//!
//! ## Approach
//!
//! 1. For each a in 2..=limit, find the smallest base `r` and power `k` such that a = r^k
//! 2. Then a^b = r^(k*b), so the canonical form is (r, k*b)
//! 3. Insert all (r, k*b) pairs into a HashSet
//! 4. The answer is the size of the set
//!
//! ## Complexity
//!
//! - Time: O(n² × log n) where n = limit (n² pairs, log n for base decomposition)
//! - Space: O(n²) for the HashSet

use std::collections::HashSet;

/// Decompose `a` into (base, exponent) where base is the smallest integer root.
///
/// For example: 8 → (2, 3) because 8 = 2³, 16 → (2, 4), 7 → (7, 1).
fn smallest_base(a: u32) -> (u32, u32) {
    // Try exponents from 2 up to log2(a)
    let max_exp = (a as f64).log2().floor() as u32;
    for exp in (2..=max_exp).rev() {
        let root = (a as f64).powf(1.0 / exp as f64).round() as u32;
        if root >= 2 && root.pow(exp) == a {
            return (root, exp);
        }
    }
    (a, 1)
}

/// Count distinct values of a^b for 2 ≤ a ≤ limit and 2 ≤ b ≤ limit.
///
/// Reduces each a^b to canonical form (smallest_base, combined_exponent) and
/// counts unique pairs via a HashSet.
///
/// # Examples
/// ```
/// use project_euler::problems::p029::count_distinct_powers;
/// assert_eq!(count_distinct_powers(5), 15);
/// assert_eq!(count_distinct_powers(100), 9183);
/// ```
pub fn count_distinct_powers(limit: u32) -> u64 {
    let mut seen = HashSet::new();

    for a in 2..=limit {
        let (base, k) = smallest_base(a);
        for b in 2..=limit {
            seen.insert((base, k * b));
        }
    }

    seen.len() as u64
}

/// Solve Problem 29: count distinct terms in a^b for 2 ≤ a,b ≤ 100.
pub fn solve() -> u64 {
    count_distinct_powers(100)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_smallest_base() {
        assert_eq!(smallest_base(2), (2, 1));
        assert_eq!(smallest_base(4), (2, 2));
        assert_eq!(smallest_base(8), (2, 3));
        assert_eq!(smallest_base(9), (3, 2));
        assert_eq!(smallest_base(16), (2, 4));
        assert_eq!(smallest_base(27), (3, 3));
        assert_eq!(smallest_base(64), (2, 6));
        assert_eq!(smallest_base(7), (7, 1));
        assert_eq!(smallest_base(100), (10, 2));
    }

    #[test]
    fn test_example_limit_5() {
        // Problem statement: 2 ≤ a ≤ 5, 2 ≤ b ≤ 5 gives 15 distinct terms
        assert_eq!(count_distinct_powers(5), 15);
    }

    #[test]
    fn test_limit_2() {
        // Only 2^2 = 4, one term
        assert_eq!(count_distinct_powers(2), 1);
    }

    #[test]
    fn test_limit_3() {
        // a=2: 2^2=4, 2^3=8
        // a=3: 3^2=9, 3^3=27
        // All distinct → 4 terms
        assert_eq!(count_distinct_powers(3), 4);
    }

    #[test]
    fn test_solve() {
        assert_eq!(solve(), 9183);
    }
}
