[package]
name = "ch13_closures_iterators"
version = "0.1.0"
edition = "2021"

# Standalone package
[workspace]

[dependencies]

[[example]]
name = "ch13_1_closures"
path = "examples/ch13_1_closures.rs"

[[example]]
name = "ch13_2_iterators"
path = "examples/ch13_2_iterators.rs"

[[example]]
name = "ch13_3_io_project"
path = "examples/ch13_3_io_project.rs"
