[package]
name = "async_concurrency"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
futures = "0.3"
trpl = "0.3.0"

[[example]]
name = "join_futures"
path = "examples/join_futures.rs"

[[example]]
name = "select_futures"
path = "examples/select_futures.rs"

[[example]]
name = "timeout_patterns"
path = "examples/timeout_patterns.rs"

[[example]]
name = "textbook_17_2"
path = "examples/book.rs"
