[package]
name = "aoc2016"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
crossterm = "0.28"
md-5 = "0.10"
mission6 = { path = "../../missions/Mission6" }
rayon = "1.10"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "benchmarks"
harness = false

[lib]
name = "aoc2016"
path = "src/lib.rs"

[[bin]]
name = "aoc2016"
path = "src/main.rs"
